---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: flame
spec:
  selector:
    matchLabels:
      app: flame
  template:
    metadata:
      labels:
        app: flame
    spec:
      serviceAccountName: flame
      containers:
        - name: flame
          image: shokohsc/flame
          ports:
            - name: http
              containerPort: 5005
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            tcpSocket:
              port: http
          resources:
            requests:
              cpu: 100m
              memory: 64M
            limits:
              cpu: 500m
              memory: 512M
